// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKI4jWAa30aA3JdIvyeVcfli-3h8mEPF0',
    appId: '1:180393661204:web:cfd42e290abf0b4e9fa801',
    messagingSenderId: '180393661204',
    projectId: 'food-bridge-223071093',
    authDomain: 'food-bridge-223071093.firebaseapp.com',
    storageBucket: 'food-bridge-223071093.firebasestorage.app',
    measurementId: 'G-HRQ72V36HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhEFD5FF6GDJGHc1hq7kEiC5F0IfU9s8g',
    appId: '1:180393661204:android:256a6bb2d949bfa69fa801',
    messagingSenderId: '180393661204',
    projectId: 'food-bridge-223071093',
    storageBucket: 'food-bridge-223071093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39ObzAxoGJZ6WKV5t5Jmuc7JILt7MHbU',
    appId: '1:180393661204:ios:94be0f4fa7c6e74f9fa801',
    messagingSenderId: '180393661204',
    projectId: 'food-bridge-223071093',
    storageBucket: 'food-bridge-223071093.firebasestorage.app',
    iosBundleId: 'com.example.foodBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39ObzAxoGJZ6WKV5t5Jmuc7JILt7MHbU',
    appId: '1:180393661204:ios:94be0f4fa7c6e74f9fa801',
    messagingSenderId: '180393661204',
    projectId: 'food-bridge-223071093',
    storageBucket: 'food-bridge-223071093.firebasestorage.app',
    iosBundleId: 'com.example.foodBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKI4jWAa30aA3JdIvyeVcfli-3h8mEPF0',
    appId: '1:180393661204:web:512c7e5f25e3ce549fa801',
    messagingSenderId: '180393661204',
    projectId: 'food-bridge-223071093',
    authDomain: 'food-bridge-223071093.firebaseapp.com',
    storageBucket: 'food-bridge-223071093.firebasestorage.app',
    measurementId: 'G-P8BSC894W7',
  );
}
